### ISSUE TITLE
mapping basemap 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/sepal_ui#13] opened 2020-08-27 17:14 UTC
geemap is a child class of both ipyleaflet and folium so we don't need to import any of these two object function 

more importantly, the basemaps  from leaflet are all natively supported like this :
```
m.add_basemap('CartoDB.Positron')
```

**Comment by ingdanielguerrero** [comment] 2020-08-27 17:22
Right!, what I was intended to do in the sepalmap class is to overwrite the default map loaded by ipyleaflet and also avoid load the second map from geemap, improving a little bit the speed when the features are loaded and the map is rendered... I was planning to discuss with the team what would be our main maps, I chose the CartoDB as native, but we could also add a 'natural' one, so we can initiate the sepalmap with one of them overwriting the other ones.

**Comment by 12rambau** [comment] 2020-08-27 17:25
I need the positron to build the AOI selector, so at the moment I'll let the user select a list of basmaps and I can put a fallback on the black_matter one

**Comment by ingdanielguerrero** [comment] 2020-08-27 17:46
I think I did not understand your question well, sorry.
And correct, `geemap.Map `is a child class from `ipyleaflet.Map`, but the imported functions there are not inherited from the Map object, are from the ipyleaflet, so in that case the import is needed.

**Comment by 12rambau** [comment] 2020-08-27 17:59
Better with an example 
with this code:
```py
def __init__(self, basemaps=None, dc=False, **kwargs):
        
        super().__init__(
            add_google_map=False, 
            center = [0,0],
            zoom = 2,
            **kwargs)
        
        #add the basemaps
        self.clear_layers()
        if len(basemaps):
            for basemap in basemaps:
                self.add_basemap(basemap)
        else:
            self.add_basemap('CartoDB.DarkMatter')
        
        #add the base controls
        self.clear_controls()    
        self.add_control(geemap.ZoomControl(position='topright'))
        self.add_control(geemap.LayersControl(position='topright'))
        self.add_control(geemap.AttributionControl(position='bottomleft'))
        self.add_control(geemap.ScaleControl(position='bottomleft', imperial=False))
        
        #specific drawing control
        self.set_drawing_controls(dc)
```

for an aoi usage you'd go:
```py
m = SepalMap(['Esri Satellite', 'CartoDB.Positron'], True)
```

and for the standart usage : (with the black_matter layer only)
```py
m = SepalMap()
```

what do you think ?

**Comment by ingdanielguerrero** [comment] 2020-08-28 07:36
Ok, I agree with your solution... but just to note that if we use the `clear_layers()` method, all layers will be removed from the current map, including the basemap, then we are adding a new 'basemap' but as a layer, so the user could turn off all the layers leaving the map empty, with the first solution the basemap cannot be removed from the UI.

**Comment by 12rambau** [comment] 2020-08-28 08:25
True, I'll make the modification and don't close the issue. We'll see with the others if it's required to have a permanent basemap

**Comment by ingdanielguerrero** [comment] 2021-04-28 23:24
I would like to re-open this issue.
It's been daunting to create own methods to remove layers without touching the main basemap instead of using just the` clear_layers()` method. I would like to propose a way to fix this drawback.

**Comment by ingdanielguerrero** [comment] 2021-04-28 23:39
Closing because I thought that if you set a fixed current map, it won't be removed when using `clear_layer` — which is not true!

**Closed by ingdanielguerrero** 2021-04-28 23:39 UTC
